cache:
  directories:
  - $HOME/.m2
language: java
jdk:
- oraclejdk8
script: ./build.sh
after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc
  -out $GPG_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc
  -out $GPG_DIR/secring.gpg -d
- $GPG_DIR/publish.sh
env:
  global:
  - GPG_DIR="`pwd`/deploy"
  - secure: rKybsGd3pfAacrdUeFxE9pZn0CJlpv5iV9Iph5iEfLYxo71Y7ytKLaKiOdSZpVPR6CRzebeP18lzqIa9A951HZltyzXofS82j/sOyBPG0v8jMR0GP5VzLLxYF7bEYpH9bPwafD87CohujzhnyhMmAo3J5Wy3HrG178/dY/cIO90QbGZRo4+UB8IkQmlVCAutDikln0XDyU2bLfRNC3opimY26tZK+GtKTGRkZBEpKW/TCDYictumaK7GS+9nFptSAEkakivCPbsJUQbm+eO6bRLOCYIMj6y/GPvtOR96vDbW3qI83mBsFP2ovmrJagrGcP/xRw1ORsAm6Fsx7W+/wmCpVwcF3Gxq8VzJbfDXN6zEL7PrjIrCKhPV+4/DehMLm80Cds/E+zrxS5OUd7370mLsLTpW0oywvwnj0qw7MdUAogwtz9gpSaD/dEvqD1zdZER53+iviTPZOzfmbpOVkyHqBfL6noi8m7h8oytmw0a0av3gncKNxL6VWDh0locEgaRkgmj5EMXtCHEfsg5N/TdyqEpmaJ7YvW6P3F0Bo1C4cbMs9hbkEwQOi3HvLlTArLrPvzBe+fTAWklwlr2XfoCh1+2AnLWeZez8lrhRHDAKmAMJja2rjSIn9GUCcVAMs2Toz6OVKT7qBtqwo4Ys8Vtvc6InAyvs/yiIY/C2C2s=
